version: 0.0
os: ubuntu-latest
files:
  - source: /
    destination: /var/www/pipeline-repository
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: hackday-codedeploy
  BeforeInstall:
    - location: scripts/application_install.sh
      timeout: 300
      runas: hackday-codedeploy
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: hackday-codedeploy