name: Refactor Code Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rector:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Ractor
        run: vendor/bin/rector process src

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply rector changes
          push_options: --force