name: Refactor Code Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Rector
        run: /vendor/bin/rector process src